
export const SHOPPINGCART_TYPE = {
    VIEW_SHOPPINGCART: {
        FETCH: 'VIEW_SHOPPINGCART_FETCH',
        SUCCESS: 'VIEW_SHOPPINGCART_FETCH_SUCCESS',
        FAILURE: 'VIEW_SHOPPINGCART_FETCH_FAILURE',
    },
    ADD_CART_ITEM: {
        FETCH: 'ADD_CART_ITEM_FETCH',
        SUCCESS: 'ADD_CART_ITEM_FETCH_SUCCESS',
        FAILURE: 'ADD_CART_ITEM_FETCH_FAILURE',
    },
    EDIT_CART_ITEM: {
        FETCH: 'EDIT_CART_ITEM_FETCH',
        SUCCESS: 'EDIT_CART_ITEM_FETCH_SUCCESS',
        FAILURE: 'EDIT_CART_ITEM_FETCH_FAILURE',
    },
    DELETE_CART_ITEM: {
        FETCH: 'DELETE_CART_ITEM_FETCH',
        SUCCESS: 'DELETE_CART_ITEM_FETCH_SUCCESS',
        FAILURE: 'DELETE_CART_ITEM_FETCH_FAILURE',
    },
    CLEAN_SHOPPINGCART: {
        FETCH: 'CLEAN_SHOPPINGCART_FETCH',
        SUCCESS: 'CLEAN_SHOPPINGCART_FETCH_SUCCESS',
        FAILURE: 'CLEAN_SHOPPINGCART_FETCH_FAILURE',
    },
    COUNT_CART_ITEM: {
        FETCH: 'COUNT_CART_ITEM_FETCH',
        SUCCESS: 'COUNT_CART_ITEM_FETCH_SUCCESS',
        FAILURE: 'COUNT_CART_ITEM_FETCH_FAILURE',
    }

};


